openapi: 3.1.0
info:
  title: OnePortal Shell Configuration API
  version: 1.0.0
  description: |
    API endpoint for retrieving the list of remote applications available to the shell.
    This configuration drives the sidebar navigation and remote app loading.
  contact:
    name: OnePortal Team

servers:
  - url: http://localhost:3000
    description: Local development (mock server)
  - url: https://api.oneportal.dev
    description: Development environment
  - url: https://api.oneportal.com
    description: Production environment

paths:
  /api/shell/config:
    get:
      operationId: getShellConfig
      summary: Get shell configuration
      description: |
        Returns the list of remote applications available to the current user.
        Shell calls this endpoint on initial load and caches the result for 5 minutes.
      tags:
        - Configuration
      responses:
        '200\:
          description: Successful response with app configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShellConfiguration'
              examples:
                twoApps:
                  summary: Two remote apps
                  value:
                    apps:
                      - id: billing
                        name: Billing Management
                        icon: /icons/billing.svg
                        entryUrl: http://localhost:5001/remoteEntry.js
                        routes:
                          - /apps/billing/*
                        sidebar: true
                        metadata:
                          description: Manage customer invoices and payments
                          order: 1
                      - id: reports
                        name: Analytics & Reports
                        icon: /icons/reports.svg
                        entryUrl: http://localhost:5002/remoteEntry.js
                        routes:
                          - /apps/reports/*
                        sidebar: true
                        metadata:
                          description: View business intelligence dashboards
                          badge: New
                          order: 2
                    version: 1.0.0
        '500\:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Internal Server Error
                message: Failed to retrieve configuration
                timestamp: 2025-10-10T12:34:56Z

components:
  schemas:
    ShellConfiguration:
      type: object
      required:
        - apps
      properties:
        apps:
          type: array
          description: List of available remote applications
          minItems: 0
          items:
            $ref: '#/components/schemas/RemoteApp'
        version:
          type: string
          description: Configuration version for cache invalidation
          example: 1.0.0

    RemoteApp:
      type: object
      required:
        - id
        - name
        - icon
        - entryUrl
        - routes
        - sidebar
      properties:
        id:
          type: string
          description: Unique application identifier
          pattern: ^[a-z0-9-]{3,50}$
          example: billing
        name:
          type: string
          description: Display name for the application
          minLength: 1
          maxLength: 100
          example: Billing Management
        icon:
          type: string
          description: Icon path (relative) or URL (absolute)
          format: uri-reference
          example: /icons/billing.svg
        entryUrl:
          type: string
          description: Module Federation remote entry point URL
          format: uri
          example: http://localhost:5001/remoteEntry.js
        routes:
          type: array
          description: Route patterns owned by this application
          minItems: 1
          items:
            type: string
            pattern: ^/apps/
            example: /apps/billing/*
        sidebar:
          type: boolean
          description: Whether to display in sidebar navigation
          example: true
        metadata:
          type: object
          description: Optional metadata for UI customization
          properties:
            description:
              type: string
              description: Tooltip or description text
              example: Manage customer invoices and payments
            badge:
              type: string
              description: Badge text (e.g., "Beta", "New")
              example: New
            order:
              type: integer
              description: Sort order in sidebar (ascending)
              minimum: 0
              example: 1

    Error:
      type: object
      required:
        - error
        - message
        - timestamp
      properties:
        error:
          type: string
          description: Error type
          example: Internal Server Error
        message:
          type: string
          description: Human-readable error message
          example: Failed to retrieve configuration
        timestamp:
          type: string
          format: date-time
          description: ISO 8601 timestamp of error
          example: 2025-10-10T12:34:56Z

tags:
  - name: Configuration
    description: Shell configuration endpoints
